# Your Name or Company
title: Volodia Laniel

# Description of your website. This is used for social sharing.
description: Volodia Laniel | Penetration Tester

# A brief blurb about yourself
content:
  - I am a Penetration Tester at UBS, previously Manager in Cyber at Deloitte
    Switzerland with several years of practice as application security expert.
  - I have experience in manual and automated penetration testing of web,
    mobile and thick client applications, infrastructure components, static
    source code analysis, reporting of security vulnerabilities and project
    management. As part of my engineering and MSc studies I worked on software
    development and on various fields of IT security such as attacking and
    securing networks and operating systems, forensic analysis, cryptography
    and reverse engineering.

# Add your social links
social:
  - platform: linkedin
    url: https://linkedin.com/in/vlaniel/?locale=en_US
  - platform: github
    url: https://github.com/vahlkar
  - platform: mastodon
    url: https://infosec.exchange/@vahlkar
  - platform: keybase
    url: https://keybase.io/vahlkar

# General settings
url: https://laniel.eu/
baseurl: "/"
markdown: kramdown
# sharing_image: share.jpg
google_analytics: "G-LK64HZXGBN" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

# Submodule configuration
destination: _site/
layouts_dir: uni/_layouts/
includes_dir: uni/_includes/
exclude:
  - uni/
